Repository graphql-kit/graphql-voyager, pull requests merged in 2023-09, with the labels that each got.

#358 Remove index.ts files
  src/components/GraphViewport.tsx
  src/components/Voyager.tsx
  src/components/doc-explorer/DocExplorer.tsx
  src/components/doc-explorer/OtherSearchResults.tsx
  src/components/doc-explorer/TypeDoc.tsx
  src/components/doc-explorer/TypeLink.tsx
  src/components/doc-explorer/TypeList.tsx
  src/components/index.tsx
  src/components/settings/RootSelector.tsx
  src/components/settings/Settings.tsx
  src/graph/index.ts
  src/graph/svg-renderer.ts
  src/graph/viewport.ts
  src/index.ts
  src/index.tsx
  src/introspection/index.ts
  src/utils/is-match.tsx
  webpack.config.ts
Labels: PR: polish 💅

#364 Add source map for library build
  webpack.config.ts
Labels: PR: feature 🚀

#360 Upgrade eslint
  package-lock.json
  package.json
Labels: PR: dependency 📦

#365 Move transformSchema into separate file
  src/introspection/introspection.ts
  src/utils/mapValues.ts
  src/utils/transformSchema.ts
Labels: PR: polish 💅

#366 various generic fixes for transformSchema
  src/utils/transformSchema.ts
Labels: PR: bug fix 🐞

#357 fix: JS middleware page
  src/middleware/render-voyager-page.ts
Labels: PR: bug fix 🐞

#367 ci: Add generation of changelog
  .github/workflows/changelog.yml
  .github/workflows/publish.yml
  .github/workflows/push.yml
  scripts/gen-changelog.ts
Labels: PR: internal 🏠

#371 Simplify propagation of display options
  src/components/GraphViewport.tsx
  src/components/Voyager.tsx
  src/graph/dot.ts
  src/graph/svg-renderer.ts
  src/graph/type-graph.ts
  src/introspection/introspection.ts
Labels: PR: polish 💅
